version: "2"
services:
  api:
    build: .
    volumes:
      - ./:/api
    ports:
      - "3000:3000"
    environment:
      ENV: production
    command: npm start
  mongo:
    image: mongo
    ports:
      - "27017:27017"
